name: Test

on: 
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Test
        run: go test -v ./...
